# Generated by Django 4.1.4 on 2022-12-09 01:47

from django.db import migrations, models
import things.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('description', models.TextField(max_length=120, verbose_name='description')),
                ('quantity', models.IntegerField(max_length=3, validators=[things.models.Thing.validate_quantity], verbose_name='quantity')),
            ],
        ),
    ]
